### ISSUE TITLE
Problems with drag & drop

### ISSUE THREAD

**Issue by mickysantomax** [JonasGessner/ImageReducer#3]
Deat Jonas,
I downloaded your project and opened it in XCode 7.2 in El Capitan os.

I'm able to run the project without errors but when I load an image with drag & drop it doesn't load it and doesn't produce the 3 images.

**Comment by JonasGessner** [comment]
The image might be in a read-only folder. Try setting breakpoints in the code that generates and writes the images to find out why it isn't working.

**Comment by algrid** [comment]
Same problem here.
```- (NSDragOperation)draggingEntered:(id<NSDraggingInfo>)sender``` is called and returns NSDragOperationCopy.
```- (BOOL)performDragOperation:(id <NSDraggingInfo>)sender``` never gets called.

**Comment by JonasGessner** [comment]
I can't replicate the issue so I can't easily find a solution. Feel free to open a pull request if you find a fix for the problem!

**Comment by xhruso00** [comment]
not sure why this happens but in my case it helped to implement following method

- (NSDragOperation)draggingUpdated:(id <NSDraggingInfo>)sender
{
    return [sender draggingSourceOperationMask];
}
